emp-tool/io/net_io_channel.h

- include files should be outside the namespace 'emp'.
- to_string -> std::to_string.

Fix compilation errors with net_io_channel

---

emp-tool/utils/constants.h

It seems socket provides the best speed and should also let Mac use socket.

Set Mac (and maybe iPhone) to unix

---

emp-tool/io/net_io_channel.h

For big output to send to another party, we should first clear the local buffer and send the big data. Otherwise, the order is not correct.

`netio` over `boost` forget to clear buffer before sending large output

---

emp-tool/garble/aes.h

It should be sufficient to put it in `emp-tool`since others are calling the binary of this one.
This one runs well also in (my) Mac.

Add AES compile-time check

---

emp-tool/io/net_io_channel.h

Otherwise, on macOS, the client does not connect correctly when the server is started before the client.
See https://stackoverflow.com/a/13110002/2945326

Close client socket before trying again

---

CMakeLists.txt
cmake/FindGMP.cmake
cmake/emp-tool-config.cmake

So that GMP can be found even if it is not in a standard location.
(Same for Boost.)

Use FindGMP instead of hardcoded paths for gmp

---

emp-tool/utils/utils_ec.h
emp-tool/utils/utils_ec.hpp

This is [thread safe as of C++11](https://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables), whereas the previous version isn't.

Make `initialized` a function-scope static variable

---

emp-tool/io/net_io_channel.h

This enables multiple NetIOs on the same port in the same process.

Close listening socket after accepting a connection

---

emp-tool/garble/aes.h
emp-tool/utils/block.h
emp-tool/utils/hash.h
emp-tool/utils/xor_tree.h

This adds [`__attribute__((target("...")))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-target-function-attribute) to functions that use instructions from specific instruction sets such as `aes`, `sse2`, `pclmul`, and so on.
The goal is to allow libraries to transitively depend on EMP, without having to pass `-maes -msse4 -mpclmul` in every compilation unit. For example, if `example.cpp` (transitively) includes `emp-tool.h`, but doesn't use any EMP functions or instantiate its templates, then `gcc example.cpp` should compile just fine.
For this to work, I had to remove the compile-time check for `__AES__` (see #37). I'm not sure that was needed, though. All it did was force users to pass `-maes` at compilation, but the resulting binaries would not run on …

Guard functions with non-standard instructions by target attributes

---

emp-tool/circuits/integer.hpp

Current `reveal<uint32_t>` and `reveal<uint64_t>` will sometimes return very large, nondeterministic positive integers that can vary between runs because they read from potentially uninitialized contents of b (line 196), since the for-loop (line 198) goes up to 32 (or 64, respectively) instead of only up to `length` as in `reveal<string>` (more specifically, `min(32, length)` or `min(64, length)`).
Thanks to @charlesdaniels for helping find this issue.

Fix reveal uint32_t and uint64_t

---

cmake/common.cmake

OPENSSL_ROOT_DIR was set twice on Macs. I don't have one, but having stared at the file for a while, it indeed looks like a typo. I left the second copy of the conditional because that's around the same place as where CMAKE_MACOSX_RPATH is zeroed.

Update common.cmake to remove dup text

---

cmake/FindGMP.cmake

CMake will try "lib" and other prefixes (and suffixes) already, per [documentation](https://cmake.org/cmake/help/latest/command/find_library.html):
> Each library name given to the NAMES option is first considered as a library file name and then considered with platform-specific prefixes (e.g. lib) and suffixes (e.g. .so). Therefore one may specify library file names such as libfoo.a directly. This can be used to locate static libraries on UNIX-like systems.

Update FindGMP.cmake to remove redundant prefix

---

cmake/common.cmake

`-Og` would be another option for debugging, but I figure `-O0` is safest.

Set optimization level by build type

---

test/float.cpp
test/float32.cpp
test/int.cpp

`std::endl` [already flushes](https://en.cppreference.com/w/cpp/io/manip/endl).

Delete flushes after endl

---

emp-tool/io/net_io_channel.h

Valgrind found a `FILE*` which wasn't freed: `fdopen` should be paired with `fclose`. `flush()` instead of `fflush(stream)` aligns the code stylistically with the alternative version of the class.

Fix small memory leak and flush instead of fflush

---

cmake/source_of_randomness.cmake

[2.8.11](https://cmake.org/cmake/help/v2.8.11/cmake.html#module:CheckCSourceRuns) even has it. I deleted the `stdio.h` include because it's not used.

Use CheckCSourceRuns instead of writing a file

---

emp-tool/utils/utils.h
emp-tool/utils/utils.hpp

It wasn't used anywhere other than emp-ot.

Remove delete_array_null, as it's redundant

---

emp-tool/utils/f2k.h

This PR closes #103.
Now, `uni_hash_coeff_gen` would specifically handle the cases when sz is small.

Fix `uni_hash_coeff_gen` for small `sz`

---

emp-tool/io/highspeed_net_io_channel.h
test/garble.cpp
test/netio.cpp

This is the first of a series of code quality fixes
Changes in this PR:
- `HighSpeedNetIO`'s constructor only takes in one port but it ends up using a second port (`port+1`). This could causes harder to catch bugs. The fix here is to update the constructor to take in two ports and update the caller to pass in the values correctly.
- Updated usage in tests
- Remove unused variables
- A lot of code style/code formatting fixes.
I highly recommend reviewing the PR with ?w=1 (ignores whitespace diff). https://github.com/emp-toolkit/emp-tool/pull/119/files?w=1

Update HighSpeedNetIO to take in two ports instead of one

---

CMakeLists.txt
emp-tool/circuits/aes_128_ctr.h

Fixed when use emp-tool as a submodule by:
- set `OUTPUT` as absolutely path
- fix `echo` command
- add `WORKING_DIRECTORY`

Fix CMakeLists.txt when use emp-tool as a submodule.

---

emp-tool/circuits/aes_128_ctr.h

Not sure why it was working before, honestly, but there's this one cast on line 53 that's necessary.

Added a cast that is necessary to compile aes_128_ctr.h if you use it as a library elsewhere

---

emp-tool/utils/prg.h

According to https://bugzilla.kernel.org/show_bug.cgi?id=85911, an AMD CPU may keep generating all zero or all one "random values" after sleep-resume.
This commit is to address this concern

Fix silent failure in CPU seed generation

---

emp-tool/circuits/aes_128_ctr.h
emp-tool/circuits/sha3_256.h

Build fails with `-DCRYPTO_IN_CIRCUIT=true` on Arch Linux (GCC 12.1.0):
```
[ 26%] Building CXX object CMakeFiles/emp-tool.dir/emp-tool/circuits/files/bristol_fashion/aes_128.txt.cpp.o
[ 29%] Building CXX object CMakeFiles/emp-tool.dir/emp-tool/circuits/files/bristol_fashion/Keccak_f.txt.cpp.o
In file included from /home/dragon/code/crypto/emp-tool2/emp-tool/circuits/files/bristol_fashion/aes_128.txt.cpp:1:
/home/dragon/code/crypto/emp-tool2/emp-tool/circuits/aes_128_ctr.h:103:14: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
103 |         std::unique_ptr<BristolFashion> circuit; // ensures circuit is deleted when this is deleted.
|              ^~~~~~~~~~
/home/dragon/code/crypto/emp-tool2/emp-tool/circuits/aes_128_ctr.h:17:1: note: ‘std::unique_ptr’ is defined in …
```

Fix build with -DCRYPTO_IN_CIRCUIT=true

---

emp-tool/circuits/aes_128_ctr.h

At the moment ```aes_128_ctr.h``` has this guard against ```input == nullptr && output == nullptr```:
https://github.com/emp-toolkit/emp-tool/blob/daa4454d5bca4861fa93166cef127a6071dc3874/emp-tool/circuits/aes_128_ctr.h#L47-L49
Unfortunately this doesn't stop the user from dereferencing a null pointer in the very next ``if`` statement:
https://github.com/emp-toolkit/emp-tool/blob/daa4454d5bca4861fa93166cef127a6071dc3874/emp-tool/circuits/aes_128_ctr.h#L50-L52
This PR simply adds a ```return -1``` if both ```input == nullptr``` and ```output == nullptr```: this prevents segmentation faults, but it preserves the error message. This should make it easy to diagnose the problem for the user, but also not cause any null dereferences.
If you want to test this, here's a failing test case:
``` …
```

Return if input  == nullptr and output == nullptr

---

emp-tool/circuits/float_circuits/float32_leq.hpp

Wire[515] is never used in the circuit, hence will contain uninitialized value. Wire[513] is the correct output wire of the circuit.

fix output wire index in float32_leq circuit 

---

emp-tool/utils/hash.h

In the local scope of put_block, sizeof(block) returned 8 instead of 16 since block was a variable of pointer type. This caused only the first half of the data to be added to the hash when using put_block. Solved by renaming the argument to something other than "block".
I found the bug because previously
```c++
int main() {
block digest_output[2];
Hash hash1;
hash1.put_block(&zero_block, 1);
hash1.put_block(&all_one_block, 1);
hash1.digest(digest_output);
cout << digest_output[0] << '\n';
Hash hash2;
block blocks[2] = {zero_block, all_one_block};
hash2.put_block(blocks, 2);
hash2.digest(digest_output);
cout << digest_output[0] << '\n';
}
```
printed two different hashes. With the fix this prints the same two hashes as expected.

Fix bug in Hash::put_block

---

emp-tool/utils/block.h

To reproduce the segfault: 
```
int main(int argc, char *argv[])
{
uint8_t *foo = new uint8_t[256];
uint8_t *bar = new uint8_t[256];
sse_trans(foo, bar, 8, 256);
```
The reason is that since nrows is unsigned, nrows - 16 is a huge number when nrows  = 8.

Fix segfault in sse_trans when nrows = 8

---

emp-tool/execution/plain_prot.h

At the moment, emp-tool treats public values as private, and adds the input wires to Bob's input: 
https://github.com/emp-toolkit/emp-tool/blob/5fbd7f7958237b553ba4b094766b182d5dfddeb3/emp-tool/execution/plain_prot.h#L32-L38
This PR marks the public values as public when being fed in. 
I'm not sure if this is all that's needed to make this work: if there's anything else @wangxiao1254, do let me know.

Add support for feeding public labels.

---

test/CMakeLists.txt

When including emp from a parent cmake project, the tests fail because ./run is not found in the path.
Also needed to set working directory at the project level (not the global cmake level) so circuit files are correctly found.

fix relative paths in tests when emp included

---

cmake/emp-base.cmake

Current code forces RPATH=0 on macOS.
This makes it much harder to use the library in non-standard install location (in particular when wanting to not install with sudo).
This commit reverts back to the default setting, which is using rpath by default.

Use default setting for RPATH on macOS

---

emp-tool/gc/halfgate_eva.h
emp-tool/gc/halfgate_gen.h

For half gates garbling and evaluating, we should instantiate the H function with `hash_cir` instead of `hash` in `MITCCRH`, in order to satisfy circular correlation robustness pointed out by:
[Better Concrete Security for Half-Gates Garbling (in the Multi-Instance Setting)](https://eprint.iacr.org/2019/1168.pdf)

[Bug fix] should call hash function with circular correlation robustness

---

emp-tool/utils/ThreadPool.h

Upgrade ThreadPool.h file to support C++20. In particular, `std::result_of` will be replaced by `std::invoke_result` accordingly.

[upgrade] ThreadPool now supports C++20

---

emp-tool/utils/prg.h
test/prg.cpp

In the original code, if `data` does not align to a block boundary, we push the ptr forward to the next boundary with `std::align`, fill the random bytes there instead, and afterwards fill in the front unaligned bytes that were skipped.
The problem with this is that the resulting byte sequence is alignment dependent. This creates a bug in `emp-agmpc` because it relies on all participants generating a consistent bool sequence here:
```cpp
block prg_key = sampleRandom(io, &prg, pool, party); // <----- All participants get the same key (seed)
PRG prgf(&prg_key);
char (*dgst)[Hash::DIGEST_SIZE] = new char[nP+1][Hash::DIGEST_SIZE];
bool * tmp = new bool[length*bucket_size]; // <--------------- Unknown alignment!
for(int i = 0; i < ssp; ++i) {
prgf.random_bool(tmp, length*bucket_size); // …
```

fix PRG alignment bug
